name: Deploy To EC2
on:
  push:
    branches:
      - main
jobs:
  My-Deploy-Job:
    runs-on: ubuntu-latest
    steps:
      - name: SSH 원격접속
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.HOST }}
          username: ubuntu
          key: ${{ secrets.PASSWORD }}
          script_stop: true
          script: |
            cd /home/ubuntu/github-actions-practice
            git pull origin main
            sudo fuser -k -n tcp 8081 || true
            nohup java -jar *.jar > ./output.log 2>&1 &
