name: Github Actions2 실행시켜보기

on:
  push:
    branches:
      - main

jobs:
  My-Deploy-Job: 
    runs-on: ubuntu-latest

    steps:
      - name: Hello World 찍기
        run: echo "Hello World"
        
      - name: 2번찍기
        run: |
          echo "Hello World2"
          echo "Hello World3"
          
      - name: github actions 자체에 저장되어 있는 변수 사용해 보기
        run: |
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
          
      - name: 아무한테 노출이 안되는 값
        run: |
          echo ${{secrets.MY_NAME}}
          echo ${{secrets.MY_PHONE}}
